Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import gio

ds = gio.read_odt('../../data/OdT/3d_horizon/Segment_ILXL_Single-line-header.dat')
ds
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mgio[39;00m
[1;32m      3[0m ds [38;5;241m=[39m gio[38;5;241m.[39mread_odt([38;5;124m'[39m[38;5;124m../../data/OdT/3d_horizon/Segment_ILXL_Single-line-header.dat[39m[38;5;124m'[39m)
[1;32m      4[0m ds

File [0;32m~/.local/lib/python3.8/site-packages/gio/__init__.py:7[0m, in [0;36m<module>[0;34m[0m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mzmap[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mrandom[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mlogo[39;00m [38;5;28;01mimport[39;00m plot
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpkg_resources[39;00m [38;5;28;01mimport[39;00m get_distribution, DistributionNotFound
[1;32m     11[0m [38;5;28;01mtry[39;00m:

File [0;32m~/.local/lib/python3.8/site-packages/gio/logo.py:8[0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;124;03m"""[39;00m
[1;32m      2[0m [38;5;124;03mMake gio's logo.[39;00m
[1;32m      3[0m 
[1;32m      4[0m [38;5;124;03mAuthor: Matt Hall[39;00m
[1;32m      5[0m [38;5;124;03mLicense: Apache 2.0[39;00m
[1;32m      6[0m [38;5;124;03m"""[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcm[39;00m [38;5;28;01mimport[39;00m get_cmap
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mhashlib[39;00m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

